/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Supermarket;

import java.awt.print.PrinterException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.TableModel;

/**
 *
 * @author User
 */
public class print2 extends javax.swing.JFrame {

    /**
     * Creates new form print1
     */
    public print2() {
        initComponents();
    }

    String ptot;
    String billno;
    public print2(String tot,String billno, TableModel model) throws PrinterException {
      initComponents();
      
      this.ptot=tot;
      this.billno=billno;
      SimpleDateFormat sdf=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
      Date date1=new Date();
      
      print_txt.setText(print_txt.getText()+ "  TECH LINK Computers & mobilephones "+"\n");
      print_txt.setText(print_txt.getText()+ "      NO.70,1st Floor,New Bustand,   "+"\n");
      print_txt.setText(print_txt.getText()+ "             Kuliyapitiya           "+"\n");
      print_txt.setText(print_txt.getText()+ "         0773688111/0713588111         \n");
      print_txt.setText(print_txt.getText()+ "\n");
      print_txt.setText(print_txt.getText()+ sdf.format(date1)+"\t"+"BillNo:"+billno+"\n");
      print_txt.setText(print_txt.getText()+"_______________________________________\n");
      print_txt.setText(print_txt.getText()+ "  Service"+"\t\t\t"+"     Amount"+"\n");
      print_txt.setText(print_txt.getText()+"_______________________________________\n");
      print_txt.setText(print_txt.getText()+ "\n");
       
      for(int i=0;i<model.getRowCount();i++){
          int no=(int)model.getValueAt(i,0);
          int no1=(int)model.getRowCount();
          String service=(String)model.getValueAt(i,1);
          String total=(String)model.getValueAt(i,2);
          
          
      print_txt.setText(print_txt.getText()+no+"  "+service+"                    "+"\n");
      print_txt.setText(print_txt.getText()+"                              "+total+"\n");    
      } 
      
      print_txt.setText(print_txt.getText()+"______________________________________\n");
      print_txt.setText(print_txt.getText()+"Sub total                     "+tot+"\n");
      print_txt.setText(print_txt.getText()+ "\n");
      print_txt.setText(print_txt.getText()+"\n");
      print_txt.setText(print_txt.getText()+ "-----------------------------------\n");
      print_txt.setText(print_txt.getText()+ "Email: techlinkkuli70@gmail.com "+"\n");
      print_txt.setText(print_txt.getText()+"*************Thank you**************\n");
      print_txt.setText(print_txt.getText()+"************Come Again**************\n");
      print_txt.print();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        print_txt = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        print_txt.setColumns(20);
        print_txt.setFont(new java.awt.Font("Monospaced", 1, 8)); // NOI18N
        print_txt.setRows(5);
        print_txt.setTabSize(6);
        print_txt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        print_txt.setPreferredSize(new java.awt.Dimension(290, 100));
        jScrollPane1.setViewportView(print_txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(print2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(print2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(print2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(print2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new print2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea print_txt;
    // End of variables declaration//GEN-END:variables
}
